site_name: ${{values.name}}
site_description: ${{values.description}}

nav:
  - Home: index.md
  - Parameters: parametros.md
  - Endpoints and methods: endpoints.md
  - Errors: errors.md

plugins:
  - techdocs-core